### ISSUE TITLE
User Settings: Change Password Functionality

### ISSUE THREAD

**Issue by ghost** [dwyl/bestevidence#128]
Linked to #24 

As a product owner
I want users to be able to change their password in their user settings
So they can keep their account up to date and secure

A user clicks 'change' password
User types in their new password and clicks save
Does a user have to enter their new password twice to ensure there are no typos?
Does a warning message that says 'min 6 characters' need to be shown?

**Requirements**

- [x] Allow users to change password in user settings

- [x] Create this functionality with the most simple and quickest design implementation (MVP) as a starting point

**Comment by ajburls** [comment]
Yes, this worked. Thanks
