### ISSUE TITLE
Missing information from searches

### ISSUE THREAD

**Issue by ajburls** [dwyl/bestevidence#225]
As a user, I want to be able to know more about the research results before I click through to them. It would be much easier to decide what is likely to be useful if the full results information from the TRIP database were shown, that is including the source publication and date

![image](https://user-images.githubusercontent.com/30235568/30600397-3a736776-9d57-11e7-8aef-23e7254570ce.png)

**Requirements**
- [x] Search must return date and source of each piece of evidence

**Comment by markwilliamfirth** [comment]
@ajburls I believe Inês and Yinka have agreed to have this feature added on

Please can you confirm that the requirement here is to display the date and source of each piece of evidence on the search results page like in the image above? Please let me know if there are any additional requirements besides these.

**Comment by ajburls** [comment]
Yes, this is what is required. It should reflect the same results as the direct TRIP database search. There are additional issues with the app but I will put these as separate issues.

**Comment by ajburls** [comment]
@markwilliamfirth Hi Mark, can you give me some indication of when the work on sprint 4 will start?

**Comment by markwilliamfirth** [comment]
@ajburls I've sent you an email about availability 👍

**Comment by markwilliamfirth** [comment]
Confirmed this will be completed by @Danwhy and @SimonLab on 21 Nov

**Comment by SimonLab** [comment]
the date and the source are now display with each publication;  screenshot of a search term on staging:
![image](https://user-images.githubusercontent.com/6057298/33101536-8e0f8596-cf10-11e7-9011-b86663a50ffe.png)

@ajburls is this working for you also?

**Comment by ajburls** [comment]
@SimonLab Yes, working on iPhone, Android and laptop. Thanks again :-)
