### ISSUE TITLE
Lazy Loading doesn't work on Firefox

### ISSUE THREAD

**Issue by ajburls** [dwyl/bestevidence#237]
The scrolling down to look at search results does not work on Firefox. This error was not identified in testing as I used Dolphin and Chrome and IE to test app.

**Comment by ajburls** [comment]
Mark, as this is something that was supposed to be delivered by Sprint 3 and is just a bug, I have changed this to sprint 4. I hope this won't take long as it works on all other browsers I have tried.

**Comment by markwilliamfirth** [comment]
Linked to https://github.com/dwyl/bestevidence/issues/32

**Comment by ajburls** [comment]
@markwilliamfirth Mark, I saw a message by Daniel, incomprehensible to me but about scrolling, and I thought I ought to mention that yesterday I observed the app would not scroll past 30 on someone's iPAD and today I tested this on my iPhone and it works. However, for the first time today it would not scroll past 20 on Samsung which it used to do (I use Dolphin browser). I tested just now on Chrome and IE on desktop and they have also developed this bug of not scrolling past 20.

**Comment by iteles** [comment]
@ajburls Thanks for your note on this. 
We recreated the same issue on our side.

**Comment by SimonLab** [comment]
@ajburls the fix has been deployed on staging. I've tested on Chrome/desktop and safary/android and everything looks ok now. Could you please check if it works on your side too? thanks

**Comment by ajburls** [comment]
@SimonLab Tested on lots of platforms, mobile and desktop and all working :-) 
thanks, Simon.
