### ISSUE TITLE
Search for "Injured dog paw" causes Internal server error

### ISSUE THREAD

**Issue by ajburls** [dwyl/bestevidence#239]
Returns internal server error 
![internal server error 23 10 2017](https://user-images.githubusercontent.com/30235568/31902605-4d78beb2-b81d-11e7-8db2-20606cb702ae.jpg)
which hasn't happened since production. Is this something to do with Dwyl starting to work on app today or is it just a bug?

**Comment by markwilliamfirth** [comment]
@ajburls it appears to be working for me - is it working on your end now?

https://www.bestevidence.info/

**Comment by ajburls** [comment]
App working for new searches. Won't work for sear h th t first generated that error, viz  "injured dog paw"



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by markwilliamfirth** [comment]
<img width="1057" alt="screen shot 2017-10-24 at 12 29 32" src="https://user-images.githubusercontent.com/5732209/31940747-1dde1e00-b8b7-11e7-90fe-7c2864aa4227.png">
<img width="1056" alt="screen shot 2017-10-24 at 12 29 43" src="https://user-images.githubusercontent.com/5732209/31940748-1dfa45f8-b8b7-11e7-82f2-fa1194f27327.png">

@ajburls it seems to work for me - could you outline the steps to replicate the issue?

**Comment by ajburls** [comment]
If I type in "Injured dog paw" (or click on the previous search of this name) and search it just returns the internal service error. I tried typint "injured dog paws" to slightly change the search and it worked.

**Comment by markwilliamfirth** [comment]
@ajburls I can't seem to replicate this issue on a Chrome browser on a desktop - what device and browser are you using?

**Comment by ajburls** [comment]
Dolphin on Samsung phone but it happens on desktop with Chrome. However, I think that once it happens for a search it always then returns same fault for that search and doesn't necessarily mean it is happening again



Sent from my Samsung Galaxy smartphone.



-------- Original message --------

**Comment by markwilliamfirth** [comment]
@ajburls I have created a new account and tested and still cannot replicate the issue - it might be an issue specific to your account - please could you try registering a new account and testing on the same device and browser to see if the issue persists?

**Comment by ajburls** [comment]
@markwilliamfirth OK, tested with new account and error doesn't occur with same search but error still in old account (perhaps to do with how database records things?)

**Comment by markwilliamfirth** [comment]
@ajburls thank you for testing - appears to be your account that is affected - we can investigate why this is - please assign a new priority label for how urgent this is

**Comment by ajburls** [comment]
I think we should not waste time on this unless the problem repeats itself so I propose to close this issue and will reopen if necessary.
