### ISSUE TITLE
How do we work with collaborators

### ISSUE THREAD

**Issue by ajburls** [dwyl/bestevidence#240]
@markwilliamfirth 
@joseempa  and I have been sharing the app with a few clinical colleagues and students and we now have some 90 odd users. (It is spreading on its own which is a good sign.)

A group who has been working on developing software to generate Criticially Appraised Topics (CATS) which was one of the functionalities we were hoping to add to the app, have offered to develop our notes into the structured notes we were wanting as CATs for us for free.

Can you explain to me how others can contribute to the modular development of the app via github and how we would retain some kind of quality control? Also how would this fit into IP/ownership issues?

**Comment by markwilliamfirth** [comment]
@ajburls 

anyone can contribute - they need to clone/download the repo, the button to do this can be seen here in the bottom right of this screenshot:

<img width="1034" alt="screen shot 2017-10-27 at 12 08 57" src="https://user-images.githubusercontent.com/5732209/32101331-aaa0d986-bb0f-11e7-862e-b9d778dcd159.png">

If they have questions or need certain permissions they can create as issue (as you do) in this repo and we will give them what they need

When they make changes they will submit them via a pull request, which must be reviewed before it is merged into the master branch of the repo - this is how we do quality control.

The IP / ownership would still be yours. The open source license will determine how people can copy and use the code

**Comment by ajburls** [comment]
Thanks. Very helpful.
