### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by ghost** [dwyl/bestevidence#244]
We need to revise and update the README to  ensure no details are missing

**Comment by markwilliamfirth** [comment]
@SimonLab is there more you want to add to this issue or are you happy with the state of the readme or should we leave it to @Danwhy to complete?

**Comment by iteles** [comment]
We need to add something about the TRIP database and the data we are utilising.

**Comment by iteles** [comment]
A simple version of what is included in this issue should also be added: https://github.com/dwyl/bestevidence/issues/154
