### ISSUE TITLE
Structured notes in BestEvidence

### ISSUE THREAD

**Issue by ajburls** [dwyl/bestevidence#266]
Currently the notes on publications just have at the bottom: remember to think about validity results and relevance. This was for reasons of cost control.
As a user of the app, it would be helpful if the notes could be structured in a way that triggers users to enter the necessary information to assess the quality of a study. This is known as critical appraisal and a critically appraised topic or CAT is a summary of the question, the paper chosen and reason for choosing it, and data calculations for the results. I have attached a file which is a standalone version of what is required for the app to help you understand what is required.
[CATmaker.zip](https://github.com/dwyl/bestevidence/files/1556255/CATmaker.zip)

**Comment by iteles** [comment]
@ajburls I believe you were going to look to book a call with myself and @joseempa on this this week so that José could take us through the requirements with his more modern version of CATmaker?

Shall we schedule this for the first week of January?

**Comment by ajburls** [comment]
@iteles As I think I said when we spoke, Jose's CATmaker system is on a private intranet within the Basque Health Service which cannot therefore be demonstrated externally. Please look at the first CATmaker programme I uploaded to get an idea of the functionality required.

**Comment by iteles** [comment]
@ajburls We've had a look but given that we don't know much about it, we're unsure as to what the user's journey would look like.

Would you please able to write a list steps that the user would take?
