### ISSUE TITLE
pop-up for evidence type covers arrow to close it in browser versions

### ISSUE THREAD

**Issue by ajburls** [dwyl/bestevidence#267]
It is not possible to close the pop up for evidence type in the online browser version of the app as it covers the little arrow to close it. The evidence type pop up works well in tested mobile app versions where it pops up as a drop down list. Please could PC version be similar.

**Comment by Cleop** [comment]
When this dropdown is clicked when a search is performed (on desktop):
<img src="https://user-images.githubusercontent.com/16775804/37277935-18ebd9b6-25de-11e8-9b31-62b05e933e53.png" width=250px />

The menu is obscuring the arrow to close it:
<img src="https://user-images.githubusercontent.com/16775804/37277959-2a67d19a-25de-11e8-8cf1-802bacd6923b.png" width=250px />

So the styling needs correcting so it can be closed.

**Comment by ajburls** [comment]
This works OK on Chrome
