### ISSUE TITLE
Use of app in protected NHS or health service environments

### ISSUE THREAD

**Issue by ajburls** [dwyl/bestevidence#28]
As NHS/OSAKITEZA user
I need to be able to access the application within NHS wifi
So that I can use it in real time at work

**Comment by SimonLab** [comment]
I will create a dummy page on Heroku like this @ajburls you can first see if Heroku is blocked or not.

**Comment by SimonLab** [comment]
Hi @ajburls could you try to access the following url https://best-evidence-app.herokuapp.com/ from the NHS wifi. I think this should work but it would be nice to confirm this first.

**Comment by ajburls** [comment]
OK @SimonLab - I am not hospital/NHS based so I have asked colleagues who are to test and @joseempa to test from his hospital in Spain. Will post results under this issue.

**Comment by markwilliamfirth** [comment]
@ajburls can you confirm the testing has been completed for this?

**Comment by ajburls** [comment]
@markwilliamfirth No - until we have the note field working we can't really test. As it stands it works but we need to be sure it doesn't block people actively recording informations

**Comment by markwilliamfirth** [comment]
Relies on #22 being completed

**Comment by SimonLab** [comment]
At this stage I'm pretty confident that there are no technical blockers for creating note from an NHS environment as some users can already access the application from these places. The only blocker would be if NHS decide in the future to restrict the access of the application but I don't see any reason why at the moment.

**Comment by ajburls** [comment]
I am going to close this issue as no-one has reported any problems and we can re-open it if issues occur.
