### ISSUE TITLE
Individual URLs for each client

### ISSUE THREAD

**Issue by RobStallion** [dwyl/bestevidence#281]
Clients would like to be able to access their own version of the application. We suggested doing this with individual URLs for each client. See https://github.com/dwyl/bestevidence/issues/260#issuecomment-375762708

Looking into the best way to solve this issue that works well for the client, developers and users alike.

**Comment by RobStallion** [comment]
One possible solution would be to allow the router scope to take an atom as an argument (e.g. scope "/:client"). 

When a client goes to their own URL (e.g. www.bestevidence.info/stbarts) we can take the `stbarts` part of the URL and check to see if they are among a list of clients that we have in the database. If so we can pull variables from the database for styling etc and allow them to use the site as they normally would.

If `stbarts` was not in the DB then we could redirect them to a _page not found_ screen as would normally happen if a user entered an incorrect URL.

**Comment by ajburls** [comment]
That sounds like it would work assuming this is all very fast from user perspective

**Comment by RobStallion** [comment]
relates to #289
