### ISSUE TITLE
Create super admin user

### ISSUE THREAD

**Issue by RobStallion** [dwyl/bestevidence#284]
As a super admin I want to be able to add new clients, colour choices and about text to the database. 

Steps to achieve

- [x] Create seed file - Will add super admin user to the database
- [x] Create super admin dash UI
  - [x] Create new route. - URL tbc
  - [x] Create new view. - Will need to have a form that can update the db with a new client/hospital/colours/etc..
  - [x] New auth plug. - This will not allow any other user to access super page. 

For more info, see https://github.com/dwyl/bestevidence/issues/260#issuecomment-375762708

**Comment by ajburls** [comment]
I can log in and create new client but can't see clients created or edit previous clients' details

**Comment by iteles** [comment]
@ajburls Agreed! That's covered in #294 and #297 

Are you happy to close this issue?

**Comment by ajburls** [comment]
@iteles yes, we can always re-open if it turns out there was a problem.
