### ISSUE TITLE
Redash queries not showing data from May onwards

### ISSUE THREAD

**Issue by ajburls** [dwyl/bestevidence#287]
Using queries via the Redash site is not working properly as data is not showing past end of April.
The data is still being collected somewhere as my recent searches do show on my app history.
I have checked the query and there is no date limit on it.
Below is a screenshot of the last page of data following updating the query today:
![image](https://user-images.githubusercontent.com/30235568/40109975-bac07436-58f6-11e8-8d44-6a1731e28e9a.png)

**Comment by RobStallion** [comment]
![image](https://user-images.githubusercontent.com/15571853/40114636-8da5b8a8-5905-11e8-9b2d-38cf7c974cc6.png)

@ajburls You can sort the queries by the titles at the top of the table. For example you can click to sort by `updated_at` which will initially return the list in order of oldest update to newest update, and will go from new to old if clicked again.

**Comment by iteles** [comment]
@ajburls In short, all the information is there, but it's not saved to the tables in exact order, so you need to order by date if you would like to see the latests information.

**Comment by ajburls** [comment]
@RobStallion Thanks, Rob. I had just assumed that they got added at the end. This is reassuring.
