### ISSUE TITLE
Ability for super admin to determine client 'slug'

### ISSUE THREAD

**Issue by iteles** [dwyl/bestevidence#288]
Sub-task of #260 

As a super admin
I want to be able to control the 'slug' for a new client (the portion of the URL that comes after `www.bestevidence.info/`)
So that for particularly long names, they are easier to remember

## Acceptance criteria
+ [x] In the 'Create new client' form, the super admin can write in their required slug
+ [x] Validation appears on this field so that if there are spaces or odd characters, there is a friendly message to say what is allowed/not allowed
+ [x] The login route for new clients corresponds to the slug and works as expected

Open question for @ajburls Do we want to allow this slug to be edited?
Maybe for now, as you're the only super admin and only you can have access to edit the slug, it makes sense to not restrict the editing of this slug for now (as you're aware of the consequences of editing this). If we decide to open up this access to anyone else, we should disallow the editing of the slug.

**Comment by ajburls** [comment]
@iteles I think it makes sense to have short slugs and therefore I will need to be able to do this. I don't see why they would need to be edited later - I am not sure that I am aware of the consequences of this - presumably once a site is in use and the URL was changed it would lock out the prior users?

**Comment by iteles** [comment]
@ajburls The only reason I would see to allow editing is if for some reason there is a typo when you initially create it or if you try out a slug and then the users don't gel with it and it needs to be changed.

The consequences could mostly be mitigated if we build in the functionality to edit:
+ We can ensure that the old URL redirects to the new URL so even if existing users try to use the previous URL, they can be redirected
+ We can ensure that we don't rely on the slug in the database for identifying users (we can use the client ID which is automatically set in the background when a client is created) so that prior users would still be able to log in no problem

It's just a question of whether we want to build this in at this stage or not.

**Comment by ajburls** [comment]
@iteles Yes, this is a good thought, customers might have strong views and it would be good to be able to respond to these. The mitigation of unwanted consequences would seem to cover the main eventualities.
Thanks

**Comment by sophielevens** [comment]
"Validation appears on this field so that if there are spaces or odd characters, there is a friendly message to say what is allowed/not allowed" 

The validation has been implemented but we have made a separate issue regarding error messages in the super admin user form #290

**Comment by ajburls** [comment]
@sophielevens I have been able to partially test in that I went in an created two new clients: a test site and Barts. However, I have no idea if this worked as I **don't** see a list of clients and their properties - I just get returned to the site to add another client (see screenshot below that was after two clients created).

![image](https://user-images.githubusercontent.com/30235568/40231889-a9f87f96-5a94-11e8-9871-54b2df6acc17.png)

**Comment by sophielevens** [comment]
Hi @ajburls, thanks for this. I completely understand what you're saying and displaying a list of the  clients and their properties is going to be covered by issue #294

**Comment by ajburls** [comment]
This all seems to be working
