### ISSUE TITLE
Superadmin dashboard: show list of clients & their properties

### ISSUE THREAD

**Issue by iteles** [dwyl/bestevidence#294]
As a super admin,
I would like to see the list of my client names
So that I can easily manage them from my dashboard as I log in.

## Acceptance criteria
+ [x] When I log in as a super admin, I see a list of all the existing clients in the system
+ [x] Clicking on this takes me to a view of the properties that have been set up for them in #289 and #288

**Comment by RobStallion** [comment]
@ajburls Please test

**Comment by ajburls** [comment]
This worked
