### ISSUE TITLE
Ability to edit the slug

### ISSUE THREAD

**Issue by iteles** [dwyl/bestevidence#295]
Derived from: https://github.com/dwyl/bestevidence/issues/288#issuecomment-389475762

As a super admin
I would like to be able to edit the slug
So that if there is a typo or a requirement to change the login URL, this can be done.

## Acceptance Criteria
+ [x] Super admins have access to an editable form where they can edit the slug name through #294
+ [x] Editing the slug name creates the new route but all functionality other than this remains as before
+ [x] Ensure that we don't rely on the slug in the database for identifying users (we can use the client ID which is automatically set in the background when a client is created) so that prior users would still be able to log in no problem
+ [ ] Investigate option to redirect old URL to new URL so even if existing users try to use the previous URL, they can be redirected (@ajburls If we do this at the app level, it would prevent you from ever re-using the 'old' URL, even if it was just a typo. The alternative is for you to set up the re-directs temporarily in your domain name provider)

**Comment by RobStallion** [comment]
The first 3 steps above can and have been completed. 

Still need to look into forth point to find best solution.

**Comment by RobStallion** [comment]
@ajburls Please test

**Comment by ajburls** [comment]
@RobStallion Not clear to me what I am supposed to be testing

**Comment by ajburls** [comment]
@RobStallion This works, so closing
