### ISSUE TITLE
Client edit form access from dashboard

### ISSUE THREAD

**Issue by iteles** [dwyl/bestevidence#297]
Sub-task of #260

As a super admin
I would like a way to access the edit form for my clients
So that I have access to update their details #295 

**Open question:** @RobStallion @sophielevens What would make most sense here? We can either click on the click name from the dashboard #294 to enter _edit_ mode (faster but more error prone maybe) OR
We can click on the client name :arrow_right: view a read-only version of the properties ➡️ click and edit button to edit/update; similarly we'd also have an edit icon ✏️ from the dashboard for quick access directly to the edit view.

**Comment by RobStallion** [comment]
@iteles Sorry, I only just realised I never replied to this question in the issue. 

After speaking in the stand up it seemed like this was the best option...

> click on the click name from the dashboard #294 to enter edit mode.

**Comment by RobStallion** [comment]
@ajburls Please test

**Comment by ajburls** [comment]
@RobStallion Yes, I can edit form and update colours and slug etc.
