### ISSUE TITLE
Badging a user as 'belonging' to a client on registration

### ISSUE THREAD

**Issue by iteles** [dwyl/bestevidence#298]
Sub-task of https://github.com/dwyl/bestevidence/issues/260#issuecomment-375762708

As a product owner
I want to be able to have users be saved in the database as 'belonging' to a specific client without necessarily giving them the ability to 'self-select' 
So that we can avoid data privacy concerns (having a list of all of our clients out in the open) and mitigate some of the risk of user error in selecting from a drop-down.

## Acceptance Criteria
+ [x] When a user registers through the client's endpoint (e.g. `/stbarts`), this automatically associates the user to the client ID
+ [x] The registration process and form contains the same fields as in the _default_ BestEvidence registration process
+ [x] In redash a product owner can run a query to see or count all of the users 'belonging' to a particular client
+ [x] If a user tries to log in through this same endpoint, they can log in as usual
+ [x] If a user tries to log in from the _default_ `www.bestevidence.info` route, they are also able to log in and view their account as usual (i.e. the URL only really matters for registration, after this their username is associated to the client ID no matter what they use)

#### Relevant portion of the scope from https://github.com/dwyl/bestevidence/issues/260#issuecomment-375762708:

We suggest that each new BE client would get their own URL (e.g. www.bestevidence.info/stbarts or stbarts.bestevidence.info) and the app would automatically recognise and log the new user as part of that institution when they create their account without them needing to select any institution (based on the URL of the page they were creating their account from).

**Comment by RobStallion** [comment]
>  In redash a product owner can run a query to see or count all of the users 'belonging' to a particular client

This step has been completed, but did not want to check it off as it cannot be tested with redash until the site has been deployed to the live server.

**Comment by RobStallion** [comment]
![image](https://user-images.githubusercontent.com/15571853/40300448-2be93592-5ce1-11e8-8f03-40569cbfc239.png)

Above is a screen shot showing a query command which will select all the users from the users table based on their client name.

**Comment by ajburls** [comment]
@RobStallion  I don't have access rights to be able to test these things

**Comment by iteles** [comment]
@ajburls You won't have access to the database in staging but in the meantime, you can 'test' this by making sure that if you log in as the user you created, the _correct_ colours are shown.

If you make St. Bart's light blue and then sign up with a user on the St. Bart's endpoint, you should then see the light blue colour scheme when you log in, whether that's from the St. Bart's endpoint or the default BE login screen. Doing this again with a different institution and a _new_ endpoint should yield different results. This is how you know your user belongs to the correct institution!
