### ISSUE TITLE
Badging the app as 'BestEvidence for `institution name`

### ISSUE THREAD

**Issue by iteles** [dwyl/bestevidence#299]
Sub-task of https://github.com/dwyl/bestevidence/issues/260#issuecomment-375762708

As a client of BestEvidence's
Wherever `BestEvidence` appears in the app, I would like this to appear as 'BestEvidence for `client name`'
So that it feels more customised to my users.

## Acceptance Criteria
+ [x] In the following places, instead of `BestEvidence`, this now appears as 'BestEvidence for `client name`':
  + [x] Alpha banner across the top of the page
  + [x] Link to 'About BestEvidence'
  + [x] Any other places you can find
+ [x] Styling on mobile or desktop breaks from a longer name, but wraps to the next line (or whatever styling makes the most sense)

**Comment by RobStallion** [comment]
@ajburls requested that we remove the word About from the about page header in order to make best evidence for 'institute name' fit well.

**Comment by RobStallion** [comment]
@ajburls Are you happy with the way this looks on mobile...

![image](https://user-images.githubusercontent.com/15571853/40539357-6e45a294-600c-11e8-976f-ddb108033c14.png)

**Comment by ajburls** [comment]
yes
