### ISSUE TITLE
Custom ‘About’ page spike - markdown or rich text?

### ISSUE THREAD

**Issue by iteles** [dwyl/bestevidence#302]
As a product owner
I feel that rich text editing may be simpler and more ‘future proof’ than markdown editing so I would like to investigate what the estimate difference for the implementation of each of these is
So that I can determine which is the best course of action

**Comment by sophielevens** [comment]
After spending some time researching, TinyMCE seems like a good approach for us on this project. I have added two scripts to the project and am now able to:

- input some about text on the super admin form
- send that content to the db 
- render the content on the front end (this still needs to be formatted)

The next step will be to look into the functionality that TinyMCE can offer us in terms of stripping the content and making it readable. 

This notification is also something that needs to be investigated further: 
![image](https://user-images.githubusercontent.com/25961258/40319446-1a5acb12-5d20-11e8-8d25-1d227e0a650e.png)

![image](https://user-images.githubusercontent.com/25961258/40318904-271fb8be-5d1e-11e8-9590-5d546439952f.png)

**Comment by iteles** [comment]
@sophielevens The other thing we'll need to investigate is the uploading of images.
Currently the first thing on this page is the City logo, which will need to be 'replaced' by the client logo.

**Comment by sophielevens** [comment]
Hi @ajburls, is the about page for every client going to be in the same format (e.g. logo on the top and text underneath)?

![image](https://user-images.githubusercontent.com/25961258/40355346-08bf2e14-5dae-11e8-8e15-72d6e166e7f9.png)

We think that this would be the most simple to implement, but also the most error-proof way to upload images.

**Comment by ajburls** [comment]
@sophielevens I think this would be fine. Would the box always be the same size (it could be that an organization wouldn't want to have their logo used and it would be better if there was not a big gap in place of the missing logo.

**Comment by sophielevens** [comment]
Thanks @ajburls, we'll make sure that gets done. I'm closing this issue in favour of #303
