### ISSUE TITLE
Add "Information specialist/librarian" as a type of user on the settings page

### ISSUE THREAD

**Issue by ajburls** [dwyl/bestevidence#306]
As a librarian using BestEvidence, 
I feel that none of the categories on the settings page represent my role

I would like to know: how much it would cost to add this additional line?

**Comment by iteles** [comment]
@ajburls I've gone into the detail of this in the email I just sent through Amanda, including cost. Let us know when you'd like us to fit this in.

**Comment by ajburls** [comment]
Having reflected on this further, I should like this new line added but additionally I would like"special to be renamed"Other" and to bring up a free text field for people to say what e.g. Journalist. Please let me know what this would cost.

**Comment by iteles** [comment]
@RobStallion For the _existing_ data, we will need to make sure that those people who have ticked `special` already are converted to appear as `other` with `special` in the input field.

**Comment by ajburls** [comment]
@RobStallion Looks, good Rob!
