### ISSUE TITLE
Internal server error when creating  a new client

### ISSUE THREAD

**Issue by iteles** [dwyl/bestevidence#319]
When logged in as the superuser and creating a new client via https://best-evidence-staging.herokuapp.com/super-admin/new, I get an internal server error message as soon as I click `Submit`

<img width="668" alt="screen shot 2018-06-04 at 12 26 23" src="https://user-images.githubusercontent.com/4185328/40915222-1f57c60a-67f3-11e8-93f7-1ab9c9dba915.png">

Steps to recreate:
1. Fill in the whole form correctly
2. Press 'Submit'

OR

1. Fill in just the name and slug, nothing else
2. Press 'Submit'

**Comment by ajburls** [comment]
@RobStallion Yes, I can now access pages, so closing.

**Comment by iteles** [comment]
This has been duplicated in #327 so closing this issue.
