### ISSUE TITLE
BEARs | Create a list of all questions for BEARs for the Intervention type

### ISSUE THREAD

**Issue by iteles** [dwyl/bestevidence#321]
@ajburls As discussed on our call last week, before we can begin the development of the BEAR/Structured notes functionality #266, we will need a comprehensive list of all the questions in each stage of the BEAR process please.

This will need to include any forks/conditional questions and the _type_ for each question (e.g. input field, checkbox, etc) so that we know exactly what to code in 😊

**Comment by ajburls** [comment]
We have decided to keep the app simple and go with the questions on the CASP checklists for all study designs. These can be downloaded at https://casp-uk.net/casp-tools-checklists/

The ones that are relevant to this first phase where we are only adding the questions for effectiveness of interventions are the RCT and sytematic review questions. 

The functionality that was captured in the spreadsheet for calculating effectiveness, previously shared. Is part B of the checklists (about results).

Preceding the use of the checklists, which serve to check the internal validity (section A) and external validity (section C) comes the section about specifying uncertainties which was on PowerPoint mock ups previously shared.

**Comment by RobStallion** [comment]
@iteles can this issue be closed now?
