### ISSUE TITLE
Create client administrator user

### ISSUE THREAD

**Issue by iteles** [dwyl/bestevidence#328]
As a super admin
I would like to allocate individuals as client administrators through their email addresses 
So that they can use the in-app messaging functionality to message their users in BE.

***Context:*** Right now, Amanda as a super user creates all of the personalised elements of client (colours, slug, about page) so we have not had to create a ***client*** admin _user_ until this stage.

## Acceptance Criteria
+ [x] When I create a new client, I can add an email address for a client administrator
+ [x] This sends them an email saying they have been invited to become a BE client administrator and that they must sign up for an account at the appropriate client URL
+ [x] Once they sign up, they can see and use BE as any standard user would _except their `Messages` area_, where they have the functionality to ***send*** messages to any and all of the users signed up to that particular client
+ [x] As a super user, I can edit the email address for a client administrator

@ajburls Does the user flow above sound correct to you? I have tried to make this as simple and time-efficient as possible.

The one question that came up for me whilst writing this new proposed functionality is that _for now_, we have not accounted for you as a super admin to be able to message client admins from within the application (as you would standard users).
This is because they do not _currently_ have an area to ***view*** messages built into the designs, only to ***send*** messages.
**Will this be an issue for this first iteration?**

**Comment by ajburls** [comment]
@iteles This sounds like a reasonable flow. What would happen if I send a message to the whole of their client group, presumably they would not know that their clients had been sent a message? I think this doesn't matter for the first iteration as there will only be a handful of clients and I could inform them by direct email, but I wouldn't want the design to be built in such a way as to preclude them being able to use BE like any other user in the future. Hope this makes sense.

**Comment by iteles** [comment]
@ajburls Exactly as you suggest, they wouldn't know at this stage.

The designs are pretty modular, in a future iteration we can easily build _your_ interactions with their users into the screen where they see _their_ interactions. 👍

**Comment by ajburls** [comment]
This doesn't work. I created an admin person for Barts using the bestevidencefeedback gmail account. 

1. that account received a message saying that I had requested a password re-set not a message of welcome as an admin person:
-----Original Message-----
From: best.evidence.dev@gmail.com <best.evidence.dev@gmail.com> 
Sent: 13 August 2018 09:52
To: bestevidencefeedback@gmail.com
Subject: Best Evidence Password Reset

  You recently requested a password reset for your Best Evidence account.

  To reset your password, follow the link
  https://best-evidence-staging.herokuapp.com//password/reset?token=kTQLigxao33lNIOsj-b0hdrxrj-3K4kocIxlt-9BXycpZFmIzGQ2Xw==
  and follow the instructions.

  If the link above does not work please copy and paste it into your browser.

  If you didn't request a password reset, you can ignore this email, or
  contact our support team via email if you have any questions bestevidencefeedback@gmail.com
----------------------------------------------------------------------------------------------------

2. when I go back to edit the barts account as super admin - the email address is not showing
-------------------------------------------------------------------------------------------------------
3. When I create a password for the feedback email address and login I just go to the app not to an admin page

**Comment by RobStallion** [comment]
Closing. Tested with @ajburls
