### ISSUE TITLE
Open low-priority questions to be tackled once initial issues are open

### ISSUE THREAD

**Issue by iteles** [dwyl/bestevidence#332]
The following are low priority open issues/questions for consideration as part of #259 that will need to be fleshed out into issues _after_ @ajburls has created the initial set of issues for the sprint:
+ [ ] Messaging shown in messages screen for client admins when there are _no_ users
+ [ ] Customised colours for chevrons and underlines throughout messaging
+ [ ] Client administrators should not be able to 'message' _themselves_, i.e. they probably shouldn't appear in their own list of users to message
+ [x] Can client admins also message individual users?

**Comment by ajburls** [comment]
@iteles In answer to last question, I think it is important that client admins should be able to message individuals.

**Comment by RobStallion** [comment]
Tested with @ajburls. Closing now
