### ISSUE TITLE
Success page - Message sent

### ISSUE THREAD

**Issue by ajburls** [dwyl/bestevidence#335]
One minor comment regarding "Success page" - the administrator doesn't have an inbox so perhaps it should read "Send another message" and open an open message page. (The can return to all other pages using menu below.)

**Comment by RobStallion** [comment]
This was updated in a [previous commit](https://github.com/dwyl/bestevidence/commit/d3022bcde2b7e2d3b9845bf025830420548a8738). 

<img src="https://user-images.githubusercontent.com/15571853/48060806-f4124100-e1b4-11e8-8505-f4cb6aafbdbd.png" width=250px />

Closing issue.
