### ISSUE TITLE
super admin email already in use in prod

### ISSUE THREAD

**Issue by RobStallion** [dwyl/bestevidence#344]
When running the seed file `priv/repo/super_admin_seeds.exs` on the `prod` server it threw up an error. The email address for `super-admin` was already in use. 

Because of this the type was inserted into the `db` but the user was not. 

We will need to run the `priv/repo/super_admin_seeds.exs` file again so that we can add a `super-admin` user, however the file will now throw an error when it tries to insert the `super-admin` type as it has been inserted into the db now. 

Need to update the `priv/repo/super_admin_seeds.exs` so that the next time we run the file (with a new email as the SA) it will allow the user to be inserted.

**Comment by ajburls** [comment]
Make the super-admin email BestEvidence.Info@gmail.com
