### ISSUE TITLE
Error when badging app in deployed version

### ISSUE THREAD

**Issue by ajburls** [dwyl/bestevidence#349]
I have just created a Barts version of the app at www.bestevidence.info with the same information as in the staging stage version. I tried to create a new account (so that I don't have a problem with it just reverting to the base app with my usual email address) to see whether the badging was successful but couldn't do so. After entering a new email address and password I get the following screen:

![image](https://user-images.githubusercontent.com/30235568/42050232-41f387b0-7b00-11e8-9329-f007ed3d76fa.png)

**Comment by RobStallion** [comment]
@ajburls This should be resolved in production now

**Comment by ajburls** [comment]
OK, now able to create a new user and login to test.
