### ISSUE TITLE
Read/unread message notifications

### ISSUE THREAD

**Issue by iteles** [dwyl/bestevidence#355]
As a user
I would like to know when I have a message that I have not yet read
So that I don't have to remember to check messages regularly myself in case there is a new one.

## Acceptance Criteria
+ [x] If a user has a message that they have not read (whether it was sent to them individually or to a group of people), they will see the red dot on the `Messages` icon in the navigation
<img width="37" alt="screen shot 2018-07-04 at 08 33 22" src="https://user-images.githubusercontent.com/4185328/42263146-11f778e6-7f65-11e8-9ddf-2d03f29632de.png">

+ [x] Once a user has clicked into their messages, all new messages are marked as read in the database and the red dot disappears from the message icon
+ [x] Super admins and client admins will not currently ever see a red dot as there is no way for them to read messages at this stage

**Comment by RobStallion** [comment]
Closing. Tested with @ajburls
