### ISSUE TITLE
Styling of messages - users and admins

### ISSUE THREAD

**Issue by iteles** [dwyl/bestevidence#366]
As the final thing to do for #259, we need to style the messages for all users.

## Acceptance Criteria - users
+ [x] `Messages` title is underlined in City red as per the below
+ [x] Date the message was sent appears above the message box, styled as per designs below
+ [x] Who the message is from appears above the message box, styled as per designs below
  + [x] Client administrators appear as `{{Client name}} Administrator`
    + [x] This still looks good (aligned correctly on the left) with particularly long names that go across two lines
  + [x] The super user appears as `BestEvidence Administrator`
+ [x] Messages have a border around them
  + [x] #4A90E2 for Super admin messages
  + [x] Whatever the main colour is for the client, for client administrator messages
+ [x] Subject appears at the top of the message box in bold
+ [ ] If a message is longer than 2 or 3 lines long, it is cut off and a `see more` link is added in the City red underneath the text, centred as per the screenshot below
+ [x] Font size and white space are as per the designs
+ [x] There is a sticky banner at the bottom of the user messages screen that tells users they can contact BE directly (as they have no option to reply to these messages)
  + [x] Text reads: 'If you would like to contact Best Evidence, please email us or call us on 02907 658309' and 'email us' is a mailto link to the feedback email account
  + [x] Banner does not hide any of the messages (particularly relevant when the content is longer than one screen and requires scrolling, the last message cannot be hidden by the banner - @Cleop was working on exactly this for CI yesterday)

<img width="189" alt="screen shot 2018-07-11 at 14 10 06" src="https://user-images.githubusercontent.com/4185328/42573740-d5280fba-8514-11e8-91ab-674bf21fe07f.png">

## Acceptance Criteria - Admins (client admins in particular!)
All styled as above except:
+ [x] There is no sticky contact banner
+ [x] Similarly to the stick banner, the 'Create new message' button cannot hide any messages content
+ [ ] Borders for messages are in the same dark grey as the text
+ [ ] There are no 'senders' (BE admin or client admin) names above the messages
<img width="195" alt="screen shot 2018-07-11 at 14 27 48" src="https://user-images.githubusercontent.com/4185328/42574614-b503671e-8516-11e8-83ae-936f4d0ade21.png">

+ [x] Screen for selecting which users to send messages to is styled according to designs
<img width="202" alt="screen shot 2018-07-11 at 14 32 51" src="https://user-images.githubusercontent.com/4185328/42574851-58b1de7c-8517-11e8-880a-52ec16925bf1.png">

**Comment by iteles** [comment]
@sophielevens Could you please provide @RobStallion with the assets for these and all other messaging screens?
In particular: 
+ Person icon for users
+ Pencil icon for new messages
+ Paper aeroplane icon for sending message button
+ Tick in the circle icon for the success page

**Comment by sophielevens** [comment]
Have checked with @RobStallion and he has all icons other than the tick for the success page. 

This is now in the Google Drive under 

Best Evidence > be-messaging > assets 

👍

**Comment by RobStallion** [comment]
Tested with @ajburls. Closing issue
