### ISSUE TITLE
Stage 1 | Collecting uncertainties homepage

### ISSUE THREAD

**Issue by iteles** [dwyl/bestevidence#367]
Part of #266 

As a user,
I want to be able to select whether I'm running a search or collecting an uncertainty (something I am not sure about and would like to critically appraise later)
So that I can capture this quickly whilst on my round (for example) and come back to it later.

## Acceptance Criteria
+ [x] Text above the search box now reads 'Question'
+ [x] Search box placeholder text now reads 'Type your uncertainty here'
+ [x] Search box now has 3 rows of space to type in as opposed to 1
+ [x] New button is in place for 'Collect your uncertainty'
  + [x] This must abide by colour changes according to client as per #289 
+ [x] Recent searches changes:
  + [x] Text for these should not be truncated
  + [x] At least 6 recent searches should appear (if the current limit is more than 6, leave as is)
  + [x] All edit icons on the right should be aligned to the far right
  + [x] Uncertainties _also_ appear in 'Recent Searches', but with a `?` icon instead of a magnifying glass **Note: this is not represented in the designs below**
  + [x] The uncertainties 'Edit' icon will take people to the new 'Notes' page (issue to be added separately and referenced here once created)
+ [x] 'About' BE now appears in the 'More' menu as opposed to at the bottom of the page
  + [x] Double check that this still works accurately for clients
+ [x] Styled as per the design below

Note @RobStallion @ajburls Please guide yourselves via the acceptance criteria and not via the design below!

<img width="347" alt="screen shot 2018-07-12 at 14 16 29" src="https://user-images.githubusercontent.com/4185328/42635539-373d351c-85de-11e8-86c9-cc3beea58c7a.png">

**Comment by ajburls** [comment]
This appears to be working but for some reason i couldn't log in as a client to test whether the about BE was showing client information.

The three choices are not aligned and still have reverse colours instead of being consistent colouring. So following done

**Comment by RobStallion** [comment]
Tested with @ajburls. Closing
