### ISSUE TITLE
Stage 2 | Alter notes form for uncertainties

### ISSUE THREAD

**Issue by iteles** [dwyl/bestevidence#371]
This issue follows on from https://github.com/dwyl/bestevidence/issues/370 and presupposes that notes will have a simpler treatment to uncertainties.

As a BE admin
I would like to have the first step of the BEAR form _resemble_ the notes form in inputs, but be enhanced with a few more features so that the user is able to easily move through the BEAR creation process
So that it is clear to users they are starting a BEAR rather than writing a note.

## Acceptance Criteria
To the _notes_ form, make the following changes:
+ [x] Add the BEAR progress bar at the top of the page 🔵-⚪️-⚪️-⚪️-⚪️-⚪️-⚪️
+ [x] Change the button text to be 'Structure Uncertainty'
+ [x] Add the link to 'save and continue later' at the bottom of the page
+ [ ] Add the BEAR menu to the top right hand side (new issue to be opened on this)
  
New notes design:
<img width="275" alt="screen shot 2018-07-19 at 12 35 28" src="https://user-images.githubusercontent.com/4185328/42940125-49696310-8b50-11e8-87c3-4e82f3e4e849.png">

**Comment by RobStallion** [comment]
Tested with @ajburls. Closing
