### ISSUE TITLE
Assets for BEAR pages do not scale well for desktop 

### ISSUE THREAD

**Issue by RobStallion** [dwyl/bestevidence#375]
This is what the asset looks like on mobile...
![image](https://user-images.githubusercontent.com/15571853/43220757-bf90037c-9042-11e8-8b8c-f7acb8859d2b.png)

And this is what it looks like on desktop...
![image](https://user-images.githubusercontent.com/15571853/43220829-ef023350-9042-11e8-8020-4004f3760f50.png)

Do we need a new asset for this or shall we just reduce the width of the existing one so it looks something like...
![image](https://user-images.githubusercontent.com/15571853/43220940-444d3526-9043-11e8-98a1-ac1a732e624f.png)

**Comment by sophielevens** [comment]
I will look into this today 👍

**Comment by sophielevens** [comment]
added SVGs to the google drive @RobStallion ✨

**Comment by RobStallion** [comment]
Excellent. These look much better 👍
