### ISSUE TITLE
Stage 2 | Paper Details

### ISSUE THREAD

**Issue by iteles** [dwyl/bestevidence#379]
As a user who has already selected my paper
I want to confirm the paper is correctly selected 
So that I can move onto the next stage of my BEAR 🐻 

<img width="263" alt="screen shot 2018-07-27 at 12 13 29" src="https://user-images.githubusercontent.com/4185328/43317882-a22b1da8-9196-11e8-8055-5b87893c73fd.png">
<img width="261" alt="screen shot 2018-07-27 at 12 13 47" src="https://user-images.githubusercontent.com/4185328/43317887-a606ad84-9196-11e8-8f02-2fe789b98574.png">

## Acceptance Criteria
+ [x] Show the updated BEAR progress bar 🔵-🔵-🔵-🔵-⚪️-⚪️-⚪️
+ [x] The following fields are _not_ input fields, but rather are pre-filled in from the selected paper:
  + [ ] Title
  + [ ] Author
  + [x] Citations
+ [x] Input area for `Why did you choose this paper?`
+ [x] `Check Validity` button which saves the information on this page and moves the user onto the next stage of the BEAR
+ [x] 'Save and continue later' link which saves the information on this page and takes the user back to the homepage

**Comment by iteles** [comment]
We'll check what comes back from the API object but we have agreed to replace the Title, Author and Citations with just the `Title` for now until we implement the DOI search.

**Comment by RobStallion** [comment]
At the moment we are only storing the title of the paper and the `TRIP API` database_id in our database. This means that we cannot easily access all the information about a paper on the paper details page. 

To avoid storing all the information of a paper in out database I have asked @ajburls if it is possible to query the `TRIP API` for a paper by id. This would let us just query for the info we need when and if we need it.

**Comment by ajburls** [comment]
@RobStallion This is working and showing the paper's title. Can this also show the information from TRIP API that appears on search results i.e. source and date? Also can this be made a link as in search results so that people can identify to which paper it refers? (Sometimes papers have very similar titles e.g. "Diabetes" and it would not be clear to which paper the BEAR pertained.

**Comment by RobStallion** [comment]
@ajburls Could you please find out if it is possible to query the TRIP API by a paper's ID. This would make it a lot easier to display the extra information you are asking for.

**Comment by iteles** [comment]
@ajburls Am I right in saying this isn't a priority for September?

**Comment by ajburls** [comment]
@iteles Yes, Rob and I agreed a compromise to save time using information from returned search results (title and source and date).

**Comment by RobStallion** [comment]
Tested with @ajburls. Closing
