### ISSUE TITLE
Stage 2 | Screen 6 - Check validity

### ISSUE THREAD

**Issue by iteles** [dwyl/bestevidence#380]
As a user who has confirmed my paper details #379
I would like to check the validity of the paper
So that this can form a key part of my 🐻  

Note: @ajburls will be sending over a sketch of this screen for improvements and the Acceptance Criteria will be updated accordingly.

## Acceptance Criteria
+ [x] Show the updated BEAR progress bar 🔵-🔵-🔵-🔵-🔵-⚪️-⚪️
+ [x] Page has the title `Check Validity`
  + @ajburls We have a note that the title here might change?
+ [x] Questions 1-6 appear as per the screenshot below, each with 3 radio options for 'Yes', 'No' or 'Can't tell'
  + Requested in https://github.com/dwyl/bestevidence/issues/377 that these be more visual, new issue to be opened on this
+ Final validity question with 'High', 'Medium' and 'Low' radio options being reviewed by @ajburls, most likely this will appear for each outcome (addition to scope)
+ [x] Input area for `Any further comments?`
+ [x] `Calculate Results` button which saves the information on this page and moves the user onto the next stage of the BEAR
+ [x] 'Save and continue later' link which saves the information on this page and takes the user back to the homepage

<img width="138" alt="screen shot 2018-07-30 at 10 41 53" src="https://user-images.githubusercontent.com/4185328/43408470-5d1024b8-9419-11e8-99fe-ccbda8ffa90d.png">

**Comment by RobStallion** [comment]
Tested with @ajburls. Closing
