### ISSUE TITLE
Database structure for BEARs

### ISSUE THREAD

**Issue by RobStallion** [dwyl/bestevidence#382]
Trying to come up with the best possible solution for the BEARs database. 

### Option 1
(note `index` relates to `index` of `pico_outcome`. Could be called `o_index`)
A `bear_questions` table and a `bear_answers` table.
![image](https://user-images.githubusercontent.com/15571853/43467578-e325cd9e-94d9-11e8-8803-425774f270c1.png)
![image](https://user-images.githubusercontent.com/15571853/43467616-fd77277e-94d9-11e8-857b-729eacb6c567.png)

### Option 2

(`in_light_of_the_above_1` and `in_light_of_the_above_9` relate to `index` of `pico_outcome`)
![image](https://user-images.githubusercontent.com/15571853/43468149-26673aa6-94db-11e8-87a0-bed2bf1cc10f.png)

#### Option 1 wins
 - Only the fields that are filled in need to be inserted into that database. All others can be ignored
 - Would be very easy to add new/update existing questions.
 - The tables would be far more concise than option 2 as option 2 will need to have a row for every input of the form. (even if no answer is given)

#### Option 2 wins 
 - Less time to implement
 - Can access all data in an easier query
 - Only need to insert/update 1 row in the database if a section has been updated.
 - Each row in the table can be a specific type. e.g. `string`,`integer`,`date`, etc. Option 1 will all need to be `strings` 

### Issues with both

With the current solution for how `pico_searches` are stored in the database, if a user ever updates their `pico_search` it will insert a new row into the db. This will mean that we will either have to re-insert/update all rows of the `bear_answers` table (the single row of the `bear_form` table if we used option 2). 

Given the above, it may be easier/more efficient to update the existing `pico_search` table. That way no other tables need to be edited. Down side to this is that there is no history of the data (I don't think that the client would mind this)

### Questions
- [x] Create a table for BEAR questions
- [x] Create migration files to add answers to table 
- [x] Display answers on relevance pages
- [x] Allow answers to be submitted in a form with the `question_id` as the key for the relevant input

### Answers
- [x] Create a table for BEAR answers
- [x] Create functions to insert into this table
  - [x] Create function for paper details page
  - [x] Create function for Check validity page
  - [x] Create function for Calculate results page
  - [x] Create function for Relevance page
- [x] Return answers for form when a user comes back to view their PICO
  - [x] Create function for paper details page
  - [x] Create function for Check validity page
  - [x] Create function for Calculate results page
  - [x] Create function for Relevance page

**Comment by RobStallion** [comment]
@nelsonic Do you have any thoughts/comments on which solution is best and why? Or if a different solution entirely is better? 

I am leaning towards option 1 right now as I feel like it will be more flexible and I don't like the idea of having a table in the db with the many fields but I am not sure if that is actually a bad thing.

**Comment by nelsonic** [comment]
@RobStallion `<option value="1" selected="selected">` 😉

**Comment by nelsonic** [comment]
@RobStallion consider adding this list to the description at the top of the file so the checklist appears in the "milestone". 😉

**Comment by RobStallion** [comment]
@nelsonic Good point 👍
