### ISSUE TITLE
Remove Notes on Publication functionality

### ISSUE THREAD

**Issue by iteles** [dwyl/bestevidence#383]
As a BE admin
Seeing as no one is using the Notes on Publications functionality and we want to encourage people to use BEARs instead, 
I would like to remove the functionality to add notes to a publication from the Quick Search results.

## Acceptance Criteria
+ [x] We can no longer add notes to a publication from the Quick Search results page
+ [x] All of the code to add these to the History and to the Notes page is removed as well.

**Comment by RobStallion** [comment]
Tested with @ajburls. Closing
