### ISSUE TITLE
Notes on Search now go straight into the first page of a BEAR

### ISSUE THREAD

**Issue by iteles** [dwyl/bestevidence#384]
As a BE admin
I want users to be able to create a BEAR from any recent search terms, _rather than_ writing un-structured notes on them (as is now the case)
So that I we can encourage users to write structured searches.

Note: If they don't want to do this, they can simply only fill in the first page of the BEAR which is in essence the same as a note on a search is presently so no functionality is being lost.

## Acceptance Criteria
+ [x] Clicking on the `+` sign next to a search term in 'Recent searches' on the landing page takes the user to the first page of a BEAR (note, this `+` icon will change, but not within this issue)
+ [x] Clicking on the `+` sign next to a search term in the 'History' on the landing page takes the user to the first page of a BEAR

**Comment by ajburls** [comment]
This works so closing issue
