### ISSUE TITLE
Calculate results page 

### ISSUE THREAD

**Issue by RobStallion** [dwyl/bestevidence#392]
@ajburls has asked for the design on this page to be updated slightly. 

The current design looks like this...
![image](https://user-images.githubusercontent.com/15571853/43639038-c84efcf8-9712-11e8-92f2-3ad7294e016d.png)

@ajburls has requested that the two boxes for control group and intervention group become one box now. Also, each outcome should have its own statistics sections.

@ajburls Please let me know if I have misunderstood anything.

**Comment by ajburls** [comment]
@RobStallion Yes, this is correct. Also, I think that the CI information would look better if the first column was right aligned so that there was one space either side of the "to".

**Comment by ajburls** [comment]
@RobStallion The results are working and the change to display of CIs looks better. Changing the two separate boxes to a 2X2 table remains to be done. I will remove please test label and lower priority of this as it is not vital for deployment of new functionality.

**Comment by RobStallion** [comment]
Tested with @ajburls. Closing this issue for the time being. Awaiting user feedback on whether or not to change the tables to a 2x2 design.
