### ISSUE TITLE
Dynamically create data for Calculate Results page

### ISSUE THREAD

**Issue by RobStallion** [dwyl/bestevidence#400]
As a user

- [x]  I would like have a section where I can calculate results for each of the outcomes I entered during the PICO search
- [x] When I have filled in the relevant input boxes and pressed the button calculate results, I would like my statistics to be calculated for me and displayed on the page.

Relates to #399
Relates to #382.

**Comment by RobStallion** [comment]
Also relates to #392

**Comment by ajburls** [comment]
@RobStallion working well on results page
