### ISSUE TITLE
Questions on Relevance page are in the incorrect order

### ISSUE THREAD

**Issue by RobStallion** [dwyl/bestevidence#427]
![image](https://user-images.githubusercontent.com/15571853/44212642-cbede580-a163-11e8-941c-6afcd9310ec7.png)

**Comment by ajburls** [comment]
@RobStallion Couldn't get this far to test... I will add as bug in new issue

**Comment by ajburls** [comment]
P.S. I wondered if anything else had actually been merged as "randomised" still spelt that way and you said you had changed this already but just had to merge.

**Comment by ajburls** [comment]
@RobStallion These questions now in right order
