### ISSUE TITLE
'Share with BestEvidence' button on Structure the Question

### ISSUE THREAD

**Issue by iteles** [dwyl/bestevidence#431]
For the 4th September, it would be a priority to get this into production.

As a BE Admin,
I would like to add a functionality for people to be able to send their questions to others
So that BE can be used as a teaching tool

The simplest version of this is just to create an email with all of the information.

## Acceptance Criteria
+ [x] At the bottom of the 'Structure the Question' screen, another link is added which reads `Share your question with BestEvidence`
+ [x] This is a `mailto` link
+ [x] Clicking on this link opens an email with:
  + [x] All of the information from _both_ the `Structure the Question` _and_ the previous page `Notes on the Uncertainty` contained in the body of the email
  + [x] bestevidencefeedback email address in cc automatically
  + [x] No message in the 'to' field for now

**Comment by RobStallion** [comment]
Tested with @ajburls. Closing
