### ISSUE TITLE
prior position appearing in list on outcomes

### ISSUE THREAD

**Issue by ajburls** [dwyl/bestevidence#443]
@RobStallion I am just testing the latest version on staging and have found a bug where the "Prior position" is being added as an outcome on the results page. Screenshot attached.

![image](https://user-images.githubusercontent.com/30235568/45147580-24d9f800-b1bd-11e8-9224-b9cd591617f2.png)

![image](https://user-images.githubusercontent.com/30235568/45147683-6c608400-b1bd-11e8-98a4-3c72194e2409.png)

**Comment by RobStallion** [comment]
I haven't been able to replicate this issue. Could you please try to replicate this again and post the steps that you took to create the error.?

**Comment by ajburls** [comment]
@RobStallion I haven't been able to reproduce. Probably operator error, so will close
