### ISSUE TITLE
Update the text in the Client admin password email

### ISSUE THREAD

**Issue by RobStallion** [dwyl/bestevidence#452]
Currently when a Client Admin is set up they receive an email saying that they have forgotten their password. 

The email works as intended but the text in the email is misleading.

- [x] Update text in email for when a client admin is created.

**Comment by ajburls** [comment]
@RobStallion 

Current message says:

  You recently requested a password reset for your Best Evidence account.

  To reset your password, follow the link
  https://best-evidence-staging.herokuapp.com//password/reset?token=kTQLigxao33lNIOsj-b0hdrxrj-3K4kocIxlt-9BXycpZFmIzGQ2Xw==
  and follow the instructions.

  If the link above does not work please copy and paste it into your browser....
----------------------------------------------------------------------------------------------------------

New message needs to say:

You have been made the client administrator for the [client name] version of the BestEvidence app. 

Please create a password at the following link: [...]

Please contact Dr Amanda Burls on 07788 124 764 or email me on BestEvidenceFeedback@gmail.com if you have any questions or problems.

**Comment by RobStallion** [comment]
@ajburls has tested this issue. The text in the email was fine but the subject line has been missed.

Next step:

- [ ] Update the subject line for the email.

**Comment by RobStallion** [comment]
@ajburls has tested this issue. The text in the email has been updated as expected.

The subject line however was not updated. See issue #460 for more info.

Closing this issue in favour of #460
