### ISSUE TITLE
Commit everything up until the end of Sprint 8 (Messaging) to production

### ISSUE THREAD

**Issue by RobStallion** [dwyl/bestevidence#455]
@ajburls has requested that Sprint 8 be put into production. 

Steps to complete
- [x] find the last commit in the commit tree for sprint 8 and branch off at that point
- [x] Resolve issues #451 & #452 
- [x] Once the above to issues have been reviewed, merge them into the sprint 8 branch
- [x] Test this branch on staging
- [x] Deploy this branch to production

**Comment by RobStallion** [comment]
[This merge](https://github.com/dwyl/bestevidence/pull/368) seems to be the last commit that references an issue from sprint 8.

In the [commit history](https://github.com/dwyl/bestevidence/commits/master?after=c0c68c1e4b5d6e31064671ad4eb22bf3a1a595e0+139) it is the last commit on Jul 13, 2018 and the next commit is the start of sprint 9 on the Jul 16, 2018.

Branching off at this point.

**Comment by RobStallion** [comment]
The [sprint-8](https://github.com/dwyl/bestevidence/tree/sprint-8) branch is now on staging and has been tested by @ajburls. 

Some `bugs fixes`/`changes` need to be made before it will be able to be put into production. The changes have been listed in issue #460.

**Comment by RobStallion** [comment]
All issues in #460 have been ticked off now. Going to redeploy the branch to staging.

**Comment by RobStallion** [comment]
All issues to do with the sprint 8 branch have now been tested by @ajburls and have been closed. 

Next steps

- [ ] Take a copy of the production database.
- [ ] Deploy sprint 8 to production.

**Comment by RobStallion** [comment]
Sprint 8 has now been deployed to production.

**Comment by ajburls** [comment]
The new version in production with badging and client adminstrators appears to working.
