### ISSUE TITLE
Message page for client user showing wrong message at bottom

### ISSUE THREAD

**Issue by ajburls** [dwyl/bestevidence#466]
@RobStallion  

![image](https://user-images.githubusercontent.com/30235568/46132764-dad1b880-c236-11e8-9699-415d5d77e5c8.png)

This was going to have  no phone number (Not sure what that phone number is)

I have a vague memory that we agreed this page was going to have the cient admin email address and copied to BE administrator....?

I have put as priority 1 as needs to be corrected before going live.

**Comment by RobStallion** [comment]
> This was going to have no phone number (Not sure what that phone number is)

@ajburls I will remove the `or call us on ...` text from the footer. 

> I have a vague memory that we agreed this page was going to have the client admin email address and copied to BE administrator....?

We cannot have the client admin's email there as all the emails are hashed so there would be no way of knowing what the client admins email actually was.

**Comment by ajburls** [comment]
Yes, now I think i remember wanting the client email address but it not being possible ;-)

**Comment by RobStallion** [comment]
Tested with @ajburls. Closing
