### ISSUE TITLE
Build failing 

### ISSUE THREAD

**Issue by RobStallion** [dwyl/bestevidence#482]
I am not sure what is causing the build to fail at the moment. I cannot see anything that would have caused this to fail. Branches that were working previously are now also failing ([see here](https://travis-ci.org/dwyl/bestevidence/builds/434686503)) which leads me to believe that the issue could be to do with travis. 

The error message we are getting is 

```
     ** (Bamboo.SMTPAdapter.SMTPError) There was a problem sending the email through SMTP.
     
     The error is :retries_exceeded
     
     More detail below:
     
     {:network_failure, "[secure]", {:error, :timeout}}
```

The error seems to be coming from [this](https://github.com/fewlinesco/bamboo_smtp) module. I have opened an issue [here](https://github.com/fewlinesco/bamboo_smtp/issues/107) to see if anyone can help shine a light on what could be causing the issue.

**Comment by nelsonic** [comment]
@RobStallion could it be that the AWS account or "from" email has changed?
(_from the commit history linked to this issue, it looks like the Travis build is passing. close issue...?_)
