### ISSUE TITLE
Internal Server Error on build (B13 Technology) 

### ISSUE THREAD

**Issue by TylerBGit** [dwyl/bestevidence#483]
Hi,

My name is Tyler from B13 Technology, Ines has instructed me to share the issues i am experiencing here.

I have set Heroku up with the same build packs, config variables (i changed these to our credentials), added Postgres and Mailgun and used the Heroku CLI to deploy. On the Heroku deploy it says "Build successful" and i can see the page with "Login" on. 

When i click Login, it gives an internal server error. When i click create account, it navigates me to the "I Agree" page. If i click "I Agree" it gives me an internal server error.

The only thing i haven't done is add the Domains. 

URL to my APP - https://bestevidence.herokuapp.com

Please could you advise?

Thanks

Tyler

**Comment by iteles** [comment]
From clicking 'Login':
![image](https://user-images.githubusercontent.com/4185328/56895441-0fce1400-6a81-11e9-8358-9752262254d0.png)

From 'I agree':
![image](https://user-images.githubusercontent.com/4185328/56895477-1f4d5d00-6a81-11e9-88af-81495ed287d4.png)

@Krizziebb Are you trying to emulate what's in production or staging?
Was it `master` branch you deployed?

**Comment by TylerBGit** [comment]
I'm trying to emulate what is in `production` and I'm using `master` to deploy from.

**Comment by TylerBGit** [comment]
If it helps i can invite you to the Heroku team.

**Comment by TylerBGit** [comment]
@iteles Any update?

**Comment by TylerBGit** [comment]
> If it helps i can invite you to the Heroku team.

@iteles i have invited you to the Heroku team

If you go to the `prod-pipe` and then production - it is the one i am currently working on.

From my initial issue post

> used the Heroku CLI to deploy

I have to use this as we use Gitlabs as our source control.

**Comment by RobStallion** [comment]
Looking at the logs now and can see the error is...
```
2019-04-30T09:04:22.248546+00:00 app[web.1]: ** (exit) an exception was raised:
2019-04-30T09:04:22.248548+00:00 app[web.1]:     ** (Postgrex.Error) ERROR 42P01 (undefined_table): relation "clients" does not exist
2019-04-30T09:04:22.248550+00:00 app[web.1]:         (ecto) lib/ecto/adapters/sql.ex:431: Ecto.Adapters.SQL.execute_and_cache/7
2019-04-30T09:04:22.248551+00:00 app[web.1]:         (ecto) lib/ecto/repo/queryable.ex:133: Ecto.Repo.Queryable.execute/5
2019-04-30T09:04:22.248553+00:00 app[web.1]:         (ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4
2019-04-30T09:04:22.248554+00:00 app[web.1]:         (ecto) lib/ecto/repo/queryable.ex:70: Ecto.Repo.Queryable.one/4
2019-04-30T09:04:22.248556+00:00 app[web.1]:         (bep) web/controllers/auth.ex:18: Bep.Auth.call/2
2019-04-30T09:04:22.248557+00:00 app[web.1]:         (bep) web/router.ex:4: Bep.Router.browser/2
2019-04-30T09:04:22.248559+00:00 app[web.1]:         (bep) web/router.ex:1: Bep.Router.match_route/4
2019-04-30T09:04:22.248560+00:00 app[web.1]:         (bep) web/router.ex:1: Bep.Router.do_call/2
```

The logs can be viewed [here](https://dashboard.heroku.com/apps/bestevidence/logs)

**Comment by TylerBGit** [comment]
@RobStallion 

I'm taking the assumption that i need to import the dump i took from your database to resolve this issue?

**Comment by RobStallion** [comment]
Morning @Krizziebb 

Initially I thought that the issue was the none of the database tables had been created...
![image](https://user-images.githubusercontent.com/15571853/56951881-d654e180-6b30-11e9-8e37-3bd72750773c.png)
_(which I thought was strange as this step should be automatically handled by the `Procfile` with the command `mix ecto.migrate`)_

I ran the `mix ecto.migrate` command manually in the heroku console and the tables were created as expected...
![image](https://user-images.githubusercontent.com/15571853/56953493-9e4f9d80-6b34-11e9-80c8-61764ec3da9b.png)

This allowed me to navigate to the landing page of the app...
![image](https://user-images.githubusercontent.com/15571853/56953550-bc1d0280-6b34-11e9-9549-1cb99bca5d98.png)

Once here I clicked the login button and get the internal server error (link you mentioned in your initial comment)

Looking at the heroku logs to see what caused this issue I saw the [logs I posted in my comment above](https://github.com/dwyl/bestevidence/issues/483#issuecomment-487874347), which said that the `clients` table did not exist. 

This was very strange to me as I had just created this table. I went back to very the database and for some reason it appears to have dropped all the tables...
![image](https://user-images.githubusercontent.com/15571853/56953765-2fbf0f80-6b35-11e9-83d3-3d41c2240103.png)

Something in the database setup is dropping the tables and this appears to be what is causing the issue you are having.

**Comment by RobStallion** [comment]
@Krizziebb are there any database commands that you are running on your end that could be causing the tables to be dropped as this does not appear to be happening in-app?

**Comment by TylerBGit** [comment]
@RobStallion 

I dropped it as i was trying to import your existing data (I specified this to @iteles) i wasn't aware you was working on the database. If you could do an import of your database that would be amazing, if not - please let me know when you are done resolving these issues.

**Comment by RobStallion** [comment]
@Krizziebb Okay. I am going to run the migration command now and see if the database tables stay up. I will keep you up to date with my progress

**Comment by RobStallion** [comment]
I have just run the `mix ecto.migrate` command again and the tables have been created again

**Comment by TylerBGit** [comment]
Brill, apologies again.

**Comment by RobStallion** [comment]
Can navigate to the landing page...
![image](https://user-images.githubusercontent.com/15571853/56954669-41a1b200-6b37-11e9-9837-16a4bd330d4a.png)

**Comment by RobStallion** [comment]
Still getting the internal server error when navigating to /sessions/new (clicking login)...
![image](https://user-images.githubusercontent.com/15571853/56954733-6c8c0600-6b37-11e9-9fb3-200dc3fa0926.png)

**Comment by RobStallion** [comment]
Latest error from the logs...
```
2019-04-30T10:01:31.361051+00:00 app[web.1]: Request: GET /sessions/new
2019-04-30T10:01:31.361052+00:00 app[web.1]: ** (exit) an exception was raised:
2019-04-30T10:01:31.361053+00:00 app[web.1]:     ** (ArgumentError) cookie store expects conn.secret_key_base to be set
2019-04-30T10:01:31.361055+00:00 app[web.1]:         (plug) lib/plug/session/cookie.ex:160: Plug.Session.COOKIE.validate_secret_key_base/1
2019-04-30T10:01:31.361056+00:00 app[web.1]:         (plug) lib/plug/session/cookie.ex:155: Plug.Session.COOKIE.derive/3
2019-04-30T10:01:31.361057+00:00 app[web.1]:         (plug) lib/plug/session/cookie.ex:103: Plug.Session.COOKIE.put/4
2019-04-30T10:01:31.361058+00:00 app[web.1]:         (plug) lib/plug/session.ex:93: anonymous fn/3 in Plug.Session.before_send/2
2019-04-30T10:01:31.361059+00:00 app[web.1]:         (elixir) lib/enum.ex:1829: Enum."-reduce/3-lists^foldl/2-0-"/3
2019-04-30T10:01:31.361061+00:00 app[web.1]:         (plug) lib/plug/conn.ex:983: Plug.Conn.run_before_send/2
2019-04-30T10:01:31.361062+00:00 app[web.1]:         (plug) lib/plug/conn.ex:392: Plug.Conn.send_resp/1
```

**Comment by RobStallion** [comment]
It appears that some of the `env variables` are missing from heroku.
`SECRET_KEY_BASE` being one of them.

**Comment by TylerBGit** [comment]
I wasn't sure what this `env variable` did or how to generate it. Could you advise how to generate this or if i'm able to use the one in your instance?.

**Comment by RobStallion** [comment]
After adding the `SECRET_KEY_BASE` I was able to navigate to `sessions/new`...
![image](https://user-images.githubusercontent.com/15571853/56955237-bfb28880-6b38-11e9-8a9a-e168c08ccb77.png)

**Comment by TylerBGit** [comment]
i'm assuming i need to do a migration of your existing database to resolve all other `internal server error` issues? e.g - [This error](https://bestevidence.herokuapp.com/users/new ).

Are you able to migrate this with the command you ran for them previous rows?.

**Comment by RobStallion** [comment]
@Krizziebb you can generate your own with the command `mix gen.secret`. You can read more about this [here](https://hexdocs.pm/phoenix/Mix.Tasks.Phx.Gen.Secret.html). 

It is used for a number of things, some of which are to help prevent CSRF attacks and session management.

**Comment by RobStallion** [comment]
@Krizziebb That's correct. If you load the database dump you took earlier it should resolve any other issues you are having. The command I ran earlier was just to set up the tables. It doesn't copy/load data from any other databases or dump files. 

When you import dump the file you have, would you be able to log the steps you take just in case there are any more errors.

**Comment by RobStallion** [comment]
It is also probably a good idea to double check the env variables again to make sure that no more are missing 👍

**Comment by TylerBGit** [comment]
@RobStallion Really appreciating the support.

I've tried importing the dump using Heroku CLI and using a presigned S3 URL. I keep on getting the below error

![image](https://user-images.githubusercontent.com/25679008/56956258-8af40080-6b3b-11e9-85d3-b85428de97da.png)

I've been doing some research on this issue to no avail. Do you have any suggestions?.

I will double check the `env variables` again. The ones i know i left out were `CA_PASS`, `BASE_URL` and `URL` as i don't want to use these yet.

**Comment by TylerBGit** [comment]
@RobStallion the docs for the above command - 

https://devcenter.heroku.com/articles/heroku-postgres-backups#restoring-backups

**Comment by TylerBGit** [comment]
@RobStallion are you able to try this from your end?

**Comment by RobStallion** [comment]
@Krizziebb Sorry for the delay in getting back to you on this. I'll take a look into this now and see if I can see what is going on

**Comment by TylerBGit** [comment]
Brilliant, thank you @RobStallion

**Comment by RobStallion** [comment]
@Krizziebb have you seen this https://devcenter.heroku.com/articles/heroku-postgres-import-export#import-to-heroku-postgres?

**Comment by TylerBGit** [comment]
@RobStallion Yes, these are the commands that i executed and got that 500 error

**Comment by TylerBGit** [comment]
@RobStallion Is it possible to try it from your end just to get a double confirmation of the error?

**Comment by TylerBGit** [comment]
@RobStallion Just an addition, here is the command i executed (Without the S3 URL)

`heroku pg:backups:restore '<S3 URL>' --app bestevidence --confirm bestevidence`

**Comment by RobStallion** [comment]
@Krizziebb I'm currently getting the same error

**Comment by TylerBGit** [comment]
@RobStallion I think this is the only way to migrate the data from your database - unless you can think of another way?

**Comment by RobStallion** [comment]
@Krizziebb I cannot think of another solution right now unfortunately. Going to continue looking into it so we can resolve this issue.

**Comment by TylerBGit** [comment]
@RobStallion i managed to resolve it!!

**Comment by RobStallion** [comment]
@Krizziebb Nice one. What steps did you take? 

Just seen the database update in my heroku tab 👍

**Comment by TylerBGit** [comment]
@RobStallion you need to set the S3 bucket and object to public, then use `heroku pg:backups:restore <s3 url that is not signed(e.g https://s3.<region code>.amazonaws.com/bucket/latest.dump) with no wrapping quotes> --app bestevidence --confirm bestevidence ` and then it will import. 

I hate inaccurate docs.

Ok i'm going to test the functionality of the app now, Thanks for the persistence @RobStallion, if there are still issues that relate to this i will add them here. Otherwise i will open a new issue.

**Comment by TylerBGit** [comment]
Are there any "BEARS" in your version of the app under the "BEARS" header? I can confirm i can create a user and login.

**Comment by RobStallion** [comment]
@Krizziebb A user creates a BEAR themselves. A BEAR allows a user to appraise a paper
