### ISSUE TITLE
My build is different to your build

### ISSUE THREAD

**Issue by TylerBGit** [dwyl/bestevidence#484]
My build seems completely different to your build once i have signed in, please see screenshots below - The first image is your App and the second is mine.

![image](https://user-images.githubusercontent.com/25679008/56969743-b5ef4c00-6b5d-11e9-8772-0be38a40a57c.png)

![image](https://user-images.githubusercontent.com/25679008/56969804-d5867480-6b5d-11e9-997d-5da6097036d0.png)

I built from the master branch.

**Comment by RobStallion** [comment]
@Krizziebb I would look at the branch ids that were deployed on heroku and try looking for the same branch in github. It's possible that the latest master branch on github is not the branch that is currently deployed (in either staging or production).

The work on creating BEARs was started but it soon became clear the the user flow was not "quite right" and as a result that feature was not deployed. 

Below is the most recent design flow I have from talks with @ajburls of how the BEAR creation flow should work...

![process-flow](https://user-images.githubusercontent.com/15571853/56970712-a53fd580-6b5f-11e9-8c25-990bddc31daa.png)

**Comment by TylerBGit** [comment]
Looking at the activity log at the latest Build and Deploy (It Is the below screenshot) - 

![image](https://user-images.githubusercontent.com/25679008/56971969-18e2e200-6b62-11e9-863d-79cc6dd302bc.png)

I compared this commit to master and got the following response - 

![image](https://user-images.githubusercontent.com/25679008/56972032-32842980-6b62-11e9-82af-ebe0f105d2d0.png)


So using the word I hate, I "assume" that my build Is the "same" as yours? Even thought it isn't.

**Comment by TylerBGit** [comment]
Any suggestions @RobStallion ?

**Comment by nelsonic** [comment]
Hi @Krizziebb 👋 
commit ref shared above in screenshot https://github.com/dwyl/bestevidence/commit/2f81327505081c308e939b0b90e45a3a81440a0d does not correspond to the _current_ `master` https://github.com/dwyl/bestevidence/commit/cf3d94a340d66164b9381a0de7bc5a5eeb4b9263
![image](https://user-images.githubusercontent.com/194400/56973210-4f216100-6b64-11e9-917c-a725ae311c42.png)

https://github.com/dwyl/bestevidence/commits/master
<img width="1146" alt="best-evidence-master-log" src="https://user-images.githubusercontent.com/194400/56973460-cce56c80-6b64-11e9-9110-42ee950dc3c3.png">

**Comment by TylerBGit** [comment]
Resolved the issue, thanks for the help @nelsonic and @RobStallion

**Comment by nelsonic** [comment]
@Krizziebb glad you got it resolved. 🎉
